### ISSUE TITLE
Refactor upload

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-datastore-cli#20]
# Description

The upload command currently gets S3 creds from a mock "authz service". Need to replace it with a real one.

# Tasks

*Requires: https://github.com/openspending/os-authz-service/issues/1*

* [x] Work with real authz service and not with mock
* [x] Optimisations? Example: the file walker needs to be more explicit (only allow files referenced in data package.json, possibly other in `archive/*` and `scripts/*`)
* [x] Tests

**Comment by roll** [comment]
@pwalsh 

So we can use only `resources/path` as files to upload?

**Comment by pwalsh** [comment]
that, plus anything under `archive/*` and `scripts/*`

**Comment by pwalsh** [comment]
DONE.
